export enum PROMO_FORM_STEPS {
    NAME = 'NAME',
    SERVICE_TYPE = 'SERVICE_TYPE',
    DESCRIPTION = 'DESCRIPTION',
    SCHEDULING = 'SCHEDULING',
    PROMOTION_TIME = 'PROMOTION_TIME',
    DISCOUNT = 'DISCOUNT',
    DISCOUNTED_PACKAGES = 'DISCOUNTED_PACKAGES'
}
